### ISSUE TITLE
macos 下 使用 Speedtest 偶发 网络拥堵

### ISSUE THREAD

**Issue by xinshangshangxin** [monsterxx03/snet#12]
1.   "proxy-scope": "bypassCN"
2.  下载 [Speedtest](https://www.speedtest.net/apps/cli)
3. `speedtest -f json -P 8 --accept-license -p`
4. 在 `progress` 大概到 40几 50几 的时候 `ctrl +c` 终止 speedtest, 但是 依然能检测到网络带宽非常高(持续5秒以上)

**Comment by xinshangshangxin** [comment]
tcpdump 的部分数据

![image](https://user-images.githubusercontent.com/8779091/81796876-9b0d3100-9540-11ea-9e0c-25121cccf946.png)

**Comment by monsterxx03** [comment]
可能是 proxy-timeout的原因，客户端每发起一个tcp连接，snet就会和上游建立一个连接，在proxy-timeout的时间内如果没数据通过，才会关闭连接, 客户端主动关闭连接也会关闭上游，试试把这个值降低

**Comment by xinshangshangxin** [comment]
建议 设置成多少呢?

**Comment by monsterxx03** [comment]
默认值是30, 其实可以不用改它, speedtest 估计是应为并发测试时候在段时间内同时建立了大量链接, 正常使用不太会有那么多.  

如果一些应用使用长连接的,需要把它的心跳包间隔设置的低于 proxy-timeout, 比如ssh的ServerAliveInterval, 不然过了 proxy-timeout 会断掉.

目前我发现有问题的是 kubectl 的 exec 命令, 不会主动发心跳, 所以过一会会断, 这种情况除了把 proxy-timeout 设置长一点我还没其他办法.

proxy-timeout 太长, 可能会让 snet 同时 hold 太多upstream connection, 太短可能会让一些使用长连接的程序断线, 只能做个 trade off.

snet 支持的几种 proxy-type 本质上都是短连接(只是读数据的时候会刷新 timeout).

**Comment by monsterxx03** [comment]
后来发现还是我的一个 bug, 有一个 error 被 ignore 了, 导致 client 主动关闭连接的行为没有检测到, 所以即使主动断开连接, snet 还是会把东西下完.

Fix in   https://github.com/monsterxx03/snet/commit/e1643f199f02fb8bcf1d66409b20c5645da31f32#diff-cd575165f84eed10d10eb1460b0927b4L84
