### ISSUE TITLE
能否检测一个网址/一个域名 是走的 fq 还是 bypass 还是 block

### ISSUE THREAD

**Issue by xinshangshangxin** [monsterxx03/snet#4]
首先, 谢谢作者 创建了 Snet, 已经切换该工具作为默认

因为从其他工具转换过来, 有强迫症想知道 哪些请求走了代理, 哪些没有

配置了
```js
{
 'proxy-scope': 'bypassCN',
}
```
能否获取 某个 域名 是用了哪个DNS查询返回的IP, 通过代理还是本地直接请求的?

**Comment by monsterxx03** [comment]
现在代码里没有直接记录, 想测试的话可以:

在 snet 开启的情况下 `dig xxx.com`, 记录下返回 ip
关闭 snet, 再次 `dig xxx.com  @114.114.114.114`,  `@` 用你设置的 cn dns,两者返回一致就是用的国内 ip, 不一致用的就是 fq dns的ip.

进一步验证可以在你的出口 server 上用 fq dns再 dig 一次.

**Comment by xinshangshangxin** [comment]
"关闭 snet, 再次 dig"

一定需要 关闭 snet 吗?

**Comment by monsterxx03** [comment]
因为 dns 的 udp 查询都被劫持了.

有个比较 tricky 的方式是 `dig xxx.com @114.114.114.114 +tcp`,  用 tcp 协议查询国内dns返回, 因为国内ip 是默认 bypass的，所以不会走 snet, 有个问题是部分国内 dns server 不支持tcp, 114 是支持的.

**Comment by xinshangshangxin** [comment]
> 因为 dns 的 udp 查询都被劫持了.
> 
> 有个比较 tricky 的方式是 `dig xxx.com @114.114.114.114 +tcp`, 用 tcp 协议查询国内dns返回, 因为国内ip 是默认 bypass的，所以不会走 snet, 有个问题是部分国内 dns server 不支持tcp, 114 是支持的.

某些域名对应的服务器只有 国外, 比如  `github.io`
```bash
dig github.io @8.8.8.8             
```
```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> github.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65415
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github.io.			IN	A

;; ANSWER SECTION:
github.io.		3530	IN	A	185.199.109.153
github.io.		3530	IN	A	185.199.111.153
github.io.		3530	IN	A	185.199.108.153
github.io.		3530	IN	A	185.199.110.153

;; Query time: 4 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Feb 24 16:43:48 CST 2020
;; MSG SIZE  rcvd: 102
```

```bash
dig github.io @223.5.5.5
```


```plain
; <<>> DiG 9.10.3-P4-Ubuntu <<>> github.io @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35732
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;github.io.			IN	A

;; ANSWER SECTION:
github.io.		900	IN	A	185.199.108.153
github.io.		900	IN	A	185.199.110.153
github.io.		900	IN	A	185.199.111.153
github.io.		900	IN	A	185.199.109.153

;; Query time: 84 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: Mon Feb 24 16:45:52 CST 2020
;; MSG SIZE  rcvd: 91
```

这种情况, 我怎么知道 是 FQ 了还是 没有?

**Comment by monsterxx03** [comment]
snet 其实是对国内 ip 段做了一个白名单, 不在白名单里的出口 tcp 流量都会被接管.

你用 linux 的话可以用 `sudo ipset test BYPASS_SNET x.x.x.x` 测试, 显示 `x.x.x.x is NOT in set BYPASS_SNET.`  就表示访问该 ip 会fq.

现在手头没 mac, 不确定mac 上怎么看.

实在很想知道也能上你的出口 server 上用 tcpdump 抓包.

**Comment by monsterxx03** [comment]
mac 上应该能用 `sudo pfctl -t BYPASS_SNET -T test x.x.x.x`

**Comment by xinshangshangxin** [comment]
> snet 其实是对国内 ip 段做了一个白名单, 不在白名单里的出口 tcp 流量都会被接管.

不是很理解这一段, 看介绍说的是 `ChinaDNS`

> [对于国内域名，国内DNS理论上返回结果更快，用户根本不再等待国外DNS的结果；对于国外域名，国内DNS返回的结果（国外IP）直接被丢弃](https://cyberloginit.com/2019/04/08/chinadns-code-analysis.html)

这个 `国内 ip 段` 作用是什么?





> mac 上应该能用 `sudo pfctl -t BYPASS_SNET -T test x.x.x.x`

```bash
sudo pfctl -t BYPASS_SNET -T test 185.199.108.153
```

```
No ALTQ support in kernel
ALTQ related functions disabled
0/1 addresses match.
```

**Comment by monsterxx03** [comment]
`No ALTQ support in kernel
ALTQ related functions disabled`

这两行是 warning, mac 上的 pfctl 是个阉割版，无视就行了.  `0/1 address match` 表示没匹配到, 说明就会翻.

当你本机发起的 dns 请求被 snet 劫持之后, 它会同时向 cn-dns, fq-dns 查询响应, 如果cn dns 的应答是一个`国内ip`, 就直接用 cn dns 的结果, 否则用 fq dns的结果. 这是 china dns 的基本原理. 国内 ip 段就是用来做判断的.

这么判断的前提是某墙对被污染的域名返回的 fake ip 都是国外ip(如果返回的是国内ip, 那有些国内网站就出毛病了嘛). 目前观测来看这么判断是靠谱的.

两个例子:
- weibo.com 有国外站, cn-dns 会返回的 ip 在国内, 所以用国内 ip
- google.com, cn-dns 返回 ip 不在国内段, 选择相信 fq-dns.

**Comment by xinshangshangxin** [comment]
多谢, 能理解了

那么这里存在一个问题, 国内IP段 更新问题, 这个是定期更新/从某个开源站更新/直接内置?

我这边的 `107.182.X.X` 的搬瓦工 网段 在我这边被判断为国内, 我只找到了 `bypass-src-ips`, 没有找到 FQ 的 ip 配置

```bash
sudo pfctl -t BYPASS_SNET -T test 107.182.1.1
```
我这边返回
`0/1 addresses match`


![image](https://user-images.githubusercontent.com/8779091/75141225-78326400-572b-11ea-8bab-e36e2ee2e0df.png)

**Comment by xinshangshangxin** [comment]
另外, 我这边有个奇葩需求

我有2个域名(A 和 B), 指向同一台国外机器
当我配置 `bypass-hosts` 为 A 时, 我请求B 也认为是国内, 这个判断是正确的还是错误的

**Comment by monsterxx03** [comment]
额,忘说了, 你这个 ip 是你的 ss-host 吧, 你的上游 server ip是个例外, 会跳过 snet, 不然会死循环(你想想)

目前 list 是从 APNIC 上下载后生成后嵌在代码里的, `make update && make`  可以更新重编译. 

我想起来就手工更新下, 不太想拆出来(主要是懒...), 其实长时间不更新问题也不大.

**Comment by xinshangshangxin** [comment]
ok, 理解

上面内容更新了, 发现其实不是因为这个IP的问题, 是因为



> 另外, 我这边有个奇葩需求
> 
> 我有2个域名(A 和 B), 指向同一台国外机器
> 当我配置 `bypass-hosts` 为 A 时, 我请求B 也认为是国内, 这个判断是正确的还是错误的

**Comment by monsterxx03** [comment]
设置 bypass-hosts 的时候, 其实是在启动前先把域名对应的 ip 解析出来,然后加进 BYPASS_SNET, 所以你 B 也被bypass 了, 因为工作在 ip 层, 这个目前无解.

把 A 加进 bypass-hosts 的目的是什么?既然它们 ip 都是同一个

**Comment by xinshangshangxin** [comment]
主要是上游server流量不够
针对A域名, 提供的主要是 下载 服务, 也就是是动辄 好几个G的文件分发
而对于B域名, 提供的是一些小流量服务, 比如 个人用的依稀工具类站点(gzip + Cache-control)

个人奇葩需求, 无需理会

**Comment by monsterxx03** [comment]
恩, 那就没办法, snet 工作在L4, 基于域名做流量分发只能在 L7 上做.

**Comment by xinshangshangxin** [comment]
恩恩, 谢谢详细解答!
