### ISSUE TITLE
upstream server 不支持 socks5吗- -

### ISSUE THREAD

**Issue by fbion** [monsterxx03/snet#5]
本机v2ray监听了一个socks5 支持udp的那种

**Comment by monsterxx03** [comment]
现在不支持, 我一般就直连远端了, 我有空加一个,也不麻烦, 不过 udp 流量还是没办法传过去

**Comment by fbion** [comment]
解析域名走ss tcp太慢了

**Comment by monsterxx03** [comment]
我一般把 dns cache 时间设长一点:

    "enable-dns-cache": true,
    "enforce-ttl": 3600

要过 dns 污染的话总要绕一下的

**Comment by monsterxx03** [comment]
Add socks5 support in v0.8.0: https://github.com/monsterxx03/snet/releases/tag/v0.8.0

Some notes in README.
